---
  - name: YUM update
    yum:
      name: '*'
      state: latest

  # - name: Install RPM packates
  #   yum:
  #     name: "{{ packages }}"

  - name: install needed rpm(s)
    package:
      name: "{{ packages | join(',') }}"
      state: present
    register: result
    until: result is succeeded

  - name: Enable SELinux
    selinux:
      policy: targeted
      state: enforcing
    register: selinux

  - name: Reboot Server after SELinux
    shell: sleep 2 && shutdown -r now
    when: selinux.reboot_required

  - name: Wait for Server to Come up
    local_action: wait_for host={{ ansible_ssh_host }} state=started
    when: selinux.reboot_required
